cuda_visible_devices: '0,1,2,3'
truncate_len: null # 用来debug，正常使用时设置为null
rounds: 1 # 用来配置多轮讨论的轮数
save_freq: 10 # 用来配置保存的频率
ans_key: ans_${run-name} # predict时生成的答案的key
save_message: false # 改成true会再记录所有agent的回答
roundk_prompt: Based on all the information, inputs, and discussions provided so far, carefully analyze and synthesize the relevant details. Think step by step, ensuring logical reasoning and completeness in your thought process. Provide your final answer clearly and concisely. # 用来配置讨论后各agent总结答案的提示

agents:
  - agent: image_agent # agent用来配置prompt，和控制参考资料中文本/图片的使用
    model: qwen2vl # model用来配置使用的模型
  - agent: text_agent
    model: llama31
  - agent: general_agent
    model: qwen2vl

sum_agent:
  agent: sum_agent # 用来汇总所有agent的回答
  model: qwen2vl