defaults:
  - train: grpo # 使用的训练方法
  - reward: dummy # 使用的reward方法
  - _self_

cuda_visible_devices: '0,1,2,3'

dataset:
  truncate_len: 500 # 用来debug，正常使用时设置为null

train:
  output_dir: training_output/Qwen25-0.5B-Instruct # 训练输出的路径
  logging_steps: 10
  # 其余参数请在train/base.yaml和train/grpo.yaml中查看

totrain_agent:
  agent: base # 用来配置agent，用于设置prompt和控制参考资料中文本/图片的使用
  model: qwen25_05B # 用来配置使用的模型