# dataset、retrieval、multi_agents的结构都可以在这个yaml中修改
# agent和model需要在对应的config文件夹下面修改

defaults:
  - doc_dataset: ldu # 改这个可以换数据集
  - retrieval: image # 改这个可以换image/text，使用retrieval时配置
  - multi_agents: mdocagent # 改这个可以换multiagent系统，使用multi_agents时配置
  - _self_

run-name: mdocagent # 实验名

doc_dataset:
  top_k: 1 # 推理时用top几
  question_key: question # 推理时用的query

retrieval:
  top_k: 10 # 检索时给出top几的结果
  text_question_key: question # 文字检索时使用的query，使用retrieval和predict时均需要
  image_question_key: question # 图片检索时使用的query，使用retrieval和predict时均需要
  cuda_visible_devices: '0'

eval_agent: # 用来测试结果
  truncate_len: null # 用来debug，正常使用时设置为null
  ans_key: ans_${run-name}
  agent: base
  model: openai