defaults:
  - base
  - _self_

# statement
# system_prompt: |
#   Please convert the given question into a vague statement. You should not give the answer to the question. Your answer should only contain the statement.
#   For example: 
#   Question: According to the report, how do 5% of the Latinos see economic upward mobility for their children?
#   Your Answer: According to the report, 5% of the Latinos see economic upward mobility for their children for some kind of reason.
#   Question: {question}

# keywords
system_prompt: |
  Please find the key elements in the question. You should not give the answer to the question. Your answer should only contain the key words.
  For example: 
  Question: According to the report, how do 5% of the Latinos see economic upward mobility for their children?
  Your Answer: 5% of the Latinos, economic upward mobility, for their children
  Question: {question}

use_text: false
use_image: false